# Generated by Django 4.0.4 on 2022-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_assurance_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottledefect',
            old_name='bottle_id',
            new_name='bottle',
        ),
        migrations.RemoveField(
            model_name='bottledefect',
            name='defect_id',
        ),
        migrations.AddField(
            model_name='bottledefect',
            name='defect_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
